# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from waves.node.grpc import assets_api_pb2 as waves_dot_node_dot_grpc_dot_assets__api__pb2


class AssetsApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInfo = channel.unary_unary(
                '/waves.node.grpc.AssetsApi/GetInfo',
                request_serializer=waves_dot_node_dot_grpc_dot_assets__api__pb2.AssetRequest.SerializeToString,
                response_deserializer=waves_dot_node_dot_grpc_dot_assets__api__pb2.AssetInfoResponse.FromString,
                )
        self.GetNFTList = channel.unary_stream(
                '/waves.node.grpc.AssetsApi/GetNFTList',
                request_serializer=waves_dot_node_dot_grpc_dot_assets__api__pb2.NFTRequest.SerializeToString,
                response_deserializer=waves_dot_node_dot_grpc_dot_assets__api__pb2.NFTResponse.FromString,
                )


class AssetsApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNFTList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AssetsApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfo,
                    request_deserializer=waves_dot_node_dot_grpc_dot_assets__api__pb2.AssetRequest.FromString,
                    response_serializer=waves_dot_node_dot_grpc_dot_assets__api__pb2.AssetInfoResponse.SerializeToString,
            ),
            'GetNFTList': grpc.unary_stream_rpc_method_handler(
                    servicer.GetNFTList,
                    request_deserializer=waves_dot_node_dot_grpc_dot_assets__api__pb2.NFTRequest.FromString,
                    response_serializer=waves_dot_node_dot_grpc_dot_assets__api__pb2.NFTResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'waves.node.grpc.AssetsApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AssetsApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/waves.node.grpc.AssetsApi/GetInfo',
            waves_dot_node_dot_grpc_dot_assets__api__pb2.AssetRequest.SerializeToString,
            waves_dot_node_dot_grpc_dot_assets__api__pb2.AssetInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNFTList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/waves.node.grpc.AssetsApi/GetNFTList',
            waves_dot_node_dot_grpc_dot_assets__api__pb2.NFTRequest.SerializeToString,
            waves_dot_node_dot_grpc_dot_assets__api__pb2.NFTResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
