# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from waves.node.grpc import blockchain_api_pb2 as waves_dot_node_dot_grpc_dot_blockchain__api__pb2


class BlockchainApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetActivationStatus = channel.unary_unary(
                '/waves.node.grpc.BlockchainApi/GetActivationStatus',
                request_serializer=waves_dot_node_dot_grpc_dot_blockchain__api__pb2.ActivationStatusRequest.SerializeToString,
                response_deserializer=waves_dot_node_dot_grpc_dot_blockchain__api__pb2.ActivationStatusResponse.FromString,
                )
        self.GetBaseTarget = channel.unary_unary(
                '/waves.node.grpc.BlockchainApi/GetBaseTarget',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=waves_dot_node_dot_grpc_dot_blockchain__api__pb2.BaseTargetResponse.FromString,
                )
        self.GetCumulativeScore = channel.unary_unary(
                '/waves.node.grpc.BlockchainApi/GetCumulativeScore',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=waves_dot_node_dot_grpc_dot_blockchain__api__pb2.ScoreResponse.FromString,
                )


class BlockchainApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetActivationStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBaseTarget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCumulativeScore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BlockchainApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetActivationStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActivationStatus,
                    request_deserializer=waves_dot_node_dot_grpc_dot_blockchain__api__pb2.ActivationStatusRequest.FromString,
                    response_serializer=waves_dot_node_dot_grpc_dot_blockchain__api__pb2.ActivationStatusResponse.SerializeToString,
            ),
            'GetBaseTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBaseTarget,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=waves_dot_node_dot_grpc_dot_blockchain__api__pb2.BaseTargetResponse.SerializeToString,
            ),
            'GetCumulativeScore': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCumulativeScore,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=waves_dot_node_dot_grpc_dot_blockchain__api__pb2.ScoreResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'waves.node.grpc.BlockchainApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BlockchainApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetActivationStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/waves.node.grpc.BlockchainApi/GetActivationStatus',
            waves_dot_node_dot_grpc_dot_blockchain__api__pb2.ActivationStatusRequest.SerializeToString,
            waves_dot_node_dot_grpc_dot_blockchain__api__pb2.ActivationStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBaseTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/waves.node.grpc.BlockchainApi/GetBaseTarget',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            waves_dot_node_dot_grpc_dot_blockchain__api__pb2.BaseTargetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCumulativeScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/waves.node.grpc.BlockchainApi/GetCumulativeScore',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            waves_dot_node_dot_grpc_dot_blockchain__api__pb2.ScoreResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
