# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/node/grpc/blocks_api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from waves import block_pb2 as waves_dot_block__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n waves/node/grpc/blocks_api.proto\x12\x0fwaves.node.grpc\x1a\x11waves/block.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"]\n\x0c\x42lockRequest\x12\x12\n\x08\x62lock_id\x18\x01 \x01(\x0cH\x00\x12\x10\n\x06height\x18\x02 \x01(\x05H\x00\x12\x1c\n\x14include_transactions\x18\x64 \x01(\x08\x42\t\n\x07request\"\xa0\x01\n\x11\x42lockRangeRequest\x12\x13\n\x0b\x66rom_height\x18\x01 \x01(\r\x12\x11\n\tto_height\x18\x02 \x01(\r\x12\x1e\n\x14generator_public_key\x18\x03 \x01(\x0cH\x00\x12\x1b\n\x11generator_address\x18\x04 \x01(\x0cH\x00\x12\x1c\n\x14include_transactions\x18\x64 \x01(\x08\x42\x08\n\x06\x66ilter\">\n\x0f\x42lockWithHeight\x12\x1b\n\x05\x62lock\x18\x01 \x01(\x0b\x32\x0c.waves.Block\x12\x0e\n\x06height\x18\x02 \x01(\r2\xfb\x01\n\tBlocksApi\x12K\n\x08GetBlock\x12\x1d.waves.node.grpc.BlockRequest\x1a .waves.node.grpc.BlockWithHeight\x12W\n\rGetBlockRange\x12\".waves.node.grpc.BlockRangeRequest\x1a .waves.node.grpc.BlockWithHeight0\x01\x12H\n\x10GetCurrentHeight\x12\x16.google.protobuf.Empty\x1a\x1c.google.protobuf.UInt32ValueBs\n\x1a\x63om.wavesplatform.api.grpcZCgithub.com/wavesplatform/gowaves/pkg/grpc/generated/waves/node/grpc\xaa\x02\x0fWaves.Node.Grpcb\x06proto3')



_BLOCKREQUEST = DESCRIPTOR.message_types_by_name['BlockRequest']
_BLOCKRANGEREQUEST = DESCRIPTOR.message_types_by_name['BlockRangeRequest']
_BLOCKWITHHEIGHT = DESCRIPTOR.message_types_by_name['BlockWithHeight']
BlockRequest = _reflection.GeneratedProtocolMessageType('BlockRequest', (_message.Message,), {
  'DESCRIPTOR' : _BLOCKREQUEST,
  '__module__' : 'waves.node.grpc.blocks_api_pb2'
  # @@protoc_insertion_point(class_scope:waves.node.grpc.BlockRequest)
  })
_sym_db.RegisterMessage(BlockRequest)

BlockRangeRequest = _reflection.GeneratedProtocolMessageType('BlockRangeRequest', (_message.Message,), {
  'DESCRIPTOR' : _BLOCKRANGEREQUEST,
  '__module__' : 'waves.node.grpc.blocks_api_pb2'
  # @@protoc_insertion_point(class_scope:waves.node.grpc.BlockRangeRequest)
  })
_sym_db.RegisterMessage(BlockRangeRequest)

BlockWithHeight = _reflection.GeneratedProtocolMessageType('BlockWithHeight', (_message.Message,), {
  'DESCRIPTOR' : _BLOCKWITHHEIGHT,
  '__module__' : 'waves.node.grpc.blocks_api_pb2'
  # @@protoc_insertion_point(class_scope:waves.node.grpc.BlockWithHeight)
  })
_sym_db.RegisterMessage(BlockWithHeight)

_BLOCKSAPI = DESCRIPTOR.services_by_name['BlocksApi']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032com.wavesplatform.api.grpcZCgithub.com/wavesplatform/gowaves/pkg/grpc/generated/waves/node/grpc\252\002\017Waves.Node.Grpc'
  _BLOCKREQUEST._serialized_start=133
  _BLOCKREQUEST._serialized_end=226
  _BLOCKRANGEREQUEST._serialized_start=229
  _BLOCKRANGEREQUEST._serialized_end=389
  _BLOCKWITHHEIGHT._serialized_start=391
  _BLOCKWITHHEIGHT._serialized_end=453
  _BLOCKSAPI._serialized_start=456
  _BLOCKSAPI._serialized_end=707
# @@protoc_insertion_point(module_scope)
