# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from waves.node.grpc import blocks_api_pb2 as waves_dot_node_dot_grpc_dot_blocks__api__pb2


class BlocksApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBlock = channel.unary_unary(
                '/waves.node.grpc.BlocksApi/GetBlock',
                request_serializer=waves_dot_node_dot_grpc_dot_blocks__api__pb2.BlockRequest.SerializeToString,
                response_deserializer=waves_dot_node_dot_grpc_dot_blocks__api__pb2.BlockWithHeight.FromString,
                )
        self.GetBlockRange = channel.unary_stream(
                '/waves.node.grpc.BlocksApi/GetBlockRange',
                request_serializer=waves_dot_node_dot_grpc_dot_blocks__api__pb2.BlockRangeRequest.SerializeToString,
                response_deserializer=waves_dot_node_dot_grpc_dot_blocks__api__pb2.BlockWithHeight.FromString,
                )
        self.GetCurrentHeight = channel.unary_unary(
                '/waves.node.grpc.BlocksApi/GetCurrentHeight',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.UInt32Value.FromString,
                )


class BlocksApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBlockRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentHeight(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BlocksApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBlock,
                    request_deserializer=waves_dot_node_dot_grpc_dot_blocks__api__pb2.BlockRequest.FromString,
                    response_serializer=waves_dot_node_dot_grpc_dot_blocks__api__pb2.BlockWithHeight.SerializeToString,
            ),
            'GetBlockRange': grpc.unary_stream_rpc_method_handler(
                    servicer.GetBlockRange,
                    request_deserializer=waves_dot_node_dot_grpc_dot_blocks__api__pb2.BlockRangeRequest.FromString,
                    response_serializer=waves_dot_node_dot_grpc_dot_blocks__api__pb2.BlockWithHeight.SerializeToString,
            ),
            'GetCurrentHeight': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentHeight,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.UInt32Value.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'waves.node.grpc.BlocksApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BlocksApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/waves.node.grpc.BlocksApi/GetBlock',
            waves_dot_node_dot_grpc_dot_blocks__api__pb2.BlockRequest.SerializeToString,
            waves_dot_node_dot_grpc_dot_blocks__api__pb2.BlockWithHeight.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBlockRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/waves.node.grpc.BlocksApi/GetBlockRange',
            waves_dot_node_dot_grpc_dot_blocks__api__pb2.BlockRangeRequest.SerializeToString,
            waves_dot_node_dot_grpc_dot_blocks__api__pb2.BlockWithHeight.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCurrentHeight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/waves.node.grpc.BlocksApi/GetCurrentHeight',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.UInt32Value.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
