# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/events/grpc/blockchain_updates.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from waves.events import events_pb2 as waves_dot_events_dot_events__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*waves/events/grpc/blockchain_updates.proto\x12\x11waves.events.grpc\x1a\x19waves/events/events.proto\"\'\n\x15GetBlockUpdateRequest\x12\x0e\n\x06height\x18\x01 \x01(\x05\"I\n\x16GetBlockUpdateResponse\x12/\n\x06update\x18\x01 \x01(\x0b\x32\x1f.waves.events.BlockchainUpdated\"E\n\x1bGetBlockUpdatesRangeRequest\x12\x13\n\x0b\x66rom_height\x18\x01 \x01(\x05\x12\x11\n\tto_height\x18\x02 \x01(\x05\"P\n\x1cGetBlockUpdatesRangeResponse\x12\x30\n\x07updates\x18\x01 \x03(\x0b\x32\x1f.waves.events.BlockchainUpdated\":\n\x10SubscribeRequest\x12\x13\n\x0b\x66rom_height\x18\x01 \x01(\x05\x12\x11\n\tto_height\x18\x02 \x01(\x05\"A\n\x0eSubscribeEvent\x12/\n\x06update\x18\x01 \x01(\x0b\x32\x1f.waves.events.BlockchainUpdated2\xcd\x02\n\x14\x42lockchainUpdatesApi\x12\x65\n\x0eGetBlockUpdate\x12(.waves.events.grpc.GetBlockUpdateRequest\x1a).waves.events.grpc.GetBlockUpdateResponse\x12w\n\x14GetBlockUpdatesRange\x12..waves.events.grpc.GetBlockUpdatesRangeRequest\x1a/.waves.events.grpc.GetBlockUpdatesRangeResponse\x12U\n\tSubscribe\x12#.waves.events.grpc.SubscribeRequest\x1a!.waves.events.grpc.SubscribeEvent0\x01\x42\x87\x01\n*com.wavesplatform.events.api.grpc.protobufZEgithub.com/wavesplatform/gowaves/pkg/grpc/generated/waves/events/grpc\xaa\x02\x11Waves.Events.Grpcb\x06proto3')



_GETBLOCKUPDATEREQUEST = DESCRIPTOR.message_types_by_name['GetBlockUpdateRequest']
_GETBLOCKUPDATERESPONSE = DESCRIPTOR.message_types_by_name['GetBlockUpdateResponse']
_GETBLOCKUPDATESRANGEREQUEST = DESCRIPTOR.message_types_by_name['GetBlockUpdatesRangeRequest']
_GETBLOCKUPDATESRANGERESPONSE = DESCRIPTOR.message_types_by_name['GetBlockUpdatesRangeResponse']
_SUBSCRIBEREQUEST = DESCRIPTOR.message_types_by_name['SubscribeRequest']
_SUBSCRIBEEVENT = DESCRIPTOR.message_types_by_name['SubscribeEvent']
GetBlockUpdateRequest = _reflection.GeneratedProtocolMessageType('GetBlockUpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETBLOCKUPDATEREQUEST,
  '__module__' : 'waves.events.grpc.blockchain_updates_pb2'
  # @@protoc_insertion_point(class_scope:waves.events.grpc.GetBlockUpdateRequest)
  })
_sym_db.RegisterMessage(GetBlockUpdateRequest)

GetBlockUpdateResponse = _reflection.GeneratedProtocolMessageType('GetBlockUpdateResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETBLOCKUPDATERESPONSE,
  '__module__' : 'waves.events.grpc.blockchain_updates_pb2'
  # @@protoc_insertion_point(class_scope:waves.events.grpc.GetBlockUpdateResponse)
  })
_sym_db.RegisterMessage(GetBlockUpdateResponse)

GetBlockUpdatesRangeRequest = _reflection.GeneratedProtocolMessageType('GetBlockUpdatesRangeRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETBLOCKUPDATESRANGEREQUEST,
  '__module__' : 'waves.events.grpc.blockchain_updates_pb2'
  # @@protoc_insertion_point(class_scope:waves.events.grpc.GetBlockUpdatesRangeRequest)
  })
_sym_db.RegisterMessage(GetBlockUpdatesRangeRequest)

GetBlockUpdatesRangeResponse = _reflection.GeneratedProtocolMessageType('GetBlockUpdatesRangeResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETBLOCKUPDATESRANGERESPONSE,
  '__module__' : 'waves.events.grpc.blockchain_updates_pb2'
  # @@protoc_insertion_point(class_scope:waves.events.grpc.GetBlockUpdatesRangeResponse)
  })
_sym_db.RegisterMessage(GetBlockUpdatesRangeResponse)

SubscribeRequest = _reflection.GeneratedProtocolMessageType('SubscribeRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBEREQUEST,
  '__module__' : 'waves.events.grpc.blockchain_updates_pb2'
  # @@protoc_insertion_point(class_scope:waves.events.grpc.SubscribeRequest)
  })
_sym_db.RegisterMessage(SubscribeRequest)

SubscribeEvent = _reflection.GeneratedProtocolMessageType('SubscribeEvent', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBEEVENT,
  '__module__' : 'waves.events.grpc.blockchain_updates_pb2'
  # @@protoc_insertion_point(class_scope:waves.events.grpc.SubscribeEvent)
  })
_sym_db.RegisterMessage(SubscribeEvent)

_BLOCKCHAINUPDATESAPI = DESCRIPTOR.services_by_name['BlockchainUpdatesApi']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n*com.wavesplatform.events.api.grpc.protobufZEgithub.com/wavesplatform/gowaves/pkg/grpc/generated/waves/events/grpc\252\002\021Waves.Events.Grpc'
  _GETBLOCKUPDATEREQUEST._serialized_start=92
  _GETBLOCKUPDATEREQUEST._serialized_end=131
  _GETBLOCKUPDATERESPONSE._serialized_start=133
  _GETBLOCKUPDATERESPONSE._serialized_end=206
  _GETBLOCKUPDATESRANGEREQUEST._serialized_start=208
  _GETBLOCKUPDATESRANGEREQUEST._serialized_end=277
  _GETBLOCKUPDATESRANGERESPONSE._serialized_start=279
  _GETBLOCKUPDATESRANGERESPONSE._serialized_end=359
  _SUBSCRIBEREQUEST._serialized_start=361
  _SUBSCRIBEREQUEST._serialized_end=419
  _SUBSCRIBEEVENT._serialized_start=421
  _SUBSCRIBEEVENT._serialized_end=486
  _BLOCKCHAINUPDATESAPI._serialized_start=489
  _BLOCKCHAINUPDATESAPI._serialized_end=822
# @@protoc_insertion_point(module_scope)
