# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/lang/dapp_meta.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1awaves/lang/dapp_meta.proto\x12\x05waves\"\xb9\x02\n\x08\x44\x41ppMeta\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x34\n\x05\x66uncs\x18\x02 \x03(\x0b\x32%.waves.DAppMeta.CallableFuncSignature\x12Z\n\"compactNameAndOriginalNamePairList\x18\x03 \x03(\x0b\x32..waves.DAppMeta.CompactNameAndOriginalNamePair\x12\x15\n\roriginalNames\x18\x04 \x03(\t\x1a&\n\x15\x43\x61llableFuncSignature\x12\r\n\x05types\x18\x01 \x01(\x0c\x1aK\n\x1e\x43ompactNameAndOriginalNamePair\x12\x13\n\x0b\x63ompactName\x18\x01 \x01(\t\x12\x14\n\x0coriginalName\x18\x02 \x01(\tBc\n\x1f\x63om.wavesplatform.protobuf.dappZ8github.com/wavesplatform/gowaves/pkg/ride/meta/generated\xaa\x02\x05Wavesb\x06proto3')



_DAPPMETA = DESCRIPTOR.message_types_by_name['DAppMeta']
_DAPPMETA_CALLABLEFUNCSIGNATURE = _DAPPMETA.nested_types_by_name['CallableFuncSignature']
_DAPPMETA_COMPACTNAMEANDORIGINALNAMEPAIR = _DAPPMETA.nested_types_by_name['CompactNameAndOriginalNamePair']
DAppMeta = _reflection.GeneratedProtocolMessageType('DAppMeta', (_message.Message,), {

  'CallableFuncSignature' : _reflection.GeneratedProtocolMessageType('CallableFuncSignature', (_message.Message,), {
    'DESCRIPTOR' : _DAPPMETA_CALLABLEFUNCSIGNATURE,
    '__module__' : 'waves.lang.dapp_meta_pb2'
    # @@protoc_insertion_point(class_scope:waves.DAppMeta.CallableFuncSignature)
    })
  ,

  'CompactNameAndOriginalNamePair' : _reflection.GeneratedProtocolMessageType('CompactNameAndOriginalNamePair', (_message.Message,), {
    'DESCRIPTOR' : _DAPPMETA_COMPACTNAMEANDORIGINALNAMEPAIR,
    '__module__' : 'waves.lang.dapp_meta_pb2'
    # @@protoc_insertion_point(class_scope:waves.DAppMeta.CompactNameAndOriginalNamePair)
    })
  ,
  'DESCRIPTOR' : _DAPPMETA,
  '__module__' : 'waves.lang.dapp_meta_pb2'
  # @@protoc_insertion_point(class_scope:waves.DAppMeta)
  })
_sym_db.RegisterMessage(DAppMeta)
_sym_db.RegisterMessage(DAppMeta.CallableFuncSignature)
_sym_db.RegisterMessage(DAppMeta.CompactNameAndOriginalNamePair)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037com.wavesplatform.protobuf.dappZ8github.com/wavesplatform/gowaves/pkg/ride/meta/generated\252\002\005Waves'
  _DAPPMETA._serialized_start=38
  _DAPPMETA._serialized_end=351
  _DAPPMETA_CALLABLEFUNCSIGNATURE._serialized_start=236
  _DAPPMETA_CALLABLEFUNCSIGNATURE._serialized_end=274
  _DAPPMETA_COMPACTNAMEANDORIGINALNAMEPAIR._serialized_start=276
  _DAPPMETA_COMPACTNAMEANDORIGINALNAMEPAIR._serialized_end=351
# @@protoc_insertion_point(module_scope)
